### ISSUE TITLE
https://www3.laqddc.com/hls/2018/04/07/BQ2cqpyZ/playlist.m3u8

### ISSUE THREAD

**Issue by zhiyou007** [Jay-Goo/M3U8Downloader#2]
下载这个直接报403，请问啥原因

**Comment by zhiyou007** [comment]
https://www3.laqddc.com/hls/2018/04/07/BQ2cqpyZ/playlist.m3u8

**Comment by JinJieGu** [comment]
是因为这个m3u8切片的地址有的是完整的url，造成了重复拼接，下个版本会处理下这种特殊情况

**Comment by JinJieGu** [comment]
问题已修复，请下载最新版本
