### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by atgui** [Jay-Goo/M3U8Downloader#3]
首先这个项目非棒，非常感谢! 下载超过4M 时会出错，不支持多个任务同时下载?

**Comment by JinJieGu** [comment]
下载超过4M指的是？
目前暂不支持多任务同时下载，因为现在m3u8切片就是多任务下载，这样的下载速度会更快一些。

**Comment by husigui** [comment]
网速超过4M 就会下载出错

**Comment by atgui** [comment]
网速超过4M 就会下载出错，我把路由限速了，在4M以下就没事了。

**Comment by JinJieGu** [comment]
日志呢？我这边网速10M的都没有问题，把日志还有下载链接贴出来

**Comment by atgui** [comment]
嗯嗯，查了下是我这边的问题，Thank you！！！
