### ISSUE TITLE
加密后的视频如何下载

### ISSUE THREAD

**Issue by menshen** [Jay-Goo/M3U8Downloader#7]
看到readme里面有关于加密的处理方式
但是我走普通的下载流程，下载加密的m3u8可以下载，但是无法播放！
是下载加密的m3u8需要走其他流程吗 ？

**Comment by yuanzaiyuanfang** [comment]
同问 可以下载不能播

**Comment by Piscen** [comment]
遇到过这个问题，如果是加密的视频，本地构建的local.m3u8中没有key路径，在重新构建的时候需要加上原来m3u8文件的key路径，这样在本地播放的时候才行

**Comment by JinJieGu** [comment]
加密解密请使用 [M3U8EncryptHelper](https://github.com/Jay-Goo/M3U8Downloader/blob/master/library/src/main/java/jaygoo/library/m3u8downloader/M3U8EncryptHelper.java)
